# Generated by Django 5.0.6 on 2024-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('adminuser', 'AdminUser'), ('Donor', 'Donor')], max_length=20),
        ),
    ]
