# Generated by Django 5.0.6 on 2024-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmedia',
            name='img',
        ),
        migrations.AddField(
            model_name='uploadmedia',
            name='images',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
