# Generated by Django 5.0.6 on 2024-06-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonation', '0002_remove_uploadmedia_img_uploadmedia_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmedia',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
