# Generated by Django 5.0.6 on 2024-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonation', '0003_alter_uploadmedia_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmedia',
            name='img',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
