# Generated by Django 5.0.6 on 2024-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneydonation', '0006_alter_uploadmedia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmedia',
            name='img',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
